<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.mutantcat.justsimple</groupId>
        <artifactId>justsimple-parent</artifactId>
        <version>4.1.1-SNAPSHOT</version>
        <relativePath>../../justsimple-parent/pom.xml</relativePath>
    </parent>

    <groupId>org.mutantcat.justsimple</groupId>
    <artifactId>justsimple-base-bundle5</artifactId>
    <name>${project.artifactId}</name>
    <packaging>pom</packaging>

    <modules>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-snack3</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-snack4</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-fastjson</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-fastjson2</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-jackson</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-jackson-xml</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-gson</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-fury</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-fory</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-hessian</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-javabin</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-protostuff</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-properties</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-kryo</module>
        <module>../../justsimple-projects/justsimple-serialization/justsimple-serialization-abc</module>


        <module>../../justsimple-projects/justsimple-testing/justsimple-test</module>
        <module>../../justsimple-projects/justsimple-testing/justsimple-test-junit4</module>
        <module>../../justsimple-projects/justsimple-testing/justsimple-test-junit5</module>
    </modules>
</project>